 create table usuario (id bigint generated by default as identity, nome varchar(255), account_expired boolean not null, account_locked boolean not null, active boolean not null, cpf varchar(255), credentials_expired boolean not null, email varchar(255), password varchar(255), roles varchar(255), telefone varchar(255), username varchar(255), primary key (id));
 create table cliente (id bigint generated by default as identity, nome varchar(255), cpf varchar(11), status smallint, data_nascimento date, primary key (id));
 create table conta (id bigint generated by default as identity, cliente_id bigint, data_abertura date, saldo decimal, primary key (id));
 alter table conta add constraint FKrp0atct0grsplospsqqay36vy foreign key (cliente_id) references cliente;
